name: Run Jupyter Notebook

on:
  push:
    branches: [ master ]  # or 'main' if that's your default
  pull_request:

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert nbformat ipykernel jupyter pandas scikit-learn matplotlib seaborn

    - name: Run notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace Random_Forest.ipynb
